name: Build katreisTherian (LÖVE Windows)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download LÖVE
        run: |
          curl -L -o love.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
          tar -xf love.zip

      - name: Build EXE
        run: |
          cmd /c copy /b love-11.5-win64\love.exe+katreisTherian.love katreisTherian.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: katreisTherian-windows
          path: katreisTherian.exe

